# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1299ca7acab3a31ad43d4c083cdd3e1ca1a12e141fb0ce9abf615d1d984ebbf158a00b6d04b0afd23f1b14c846c3d82a4195f30a738fa16f6358a081d7feb048

test:
  secret_key_base: d2f70167ca8646ecdf8bea5065c81cd2fb8d7daf699e6fe70c2b1dd96ec368431a501021ca64de1e7ad276f462c810cb56c82dc4c12a8c2a0f1254d62d67ba8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
